Add tracking.

diff --git a/do-cli-speedtest b/do-cli-speedtest
--- a/do-cli-speedtest
+++ b/do-cli-speedtest
@@ -11,6 +11,7 @@ dataCenters=(speedtest-{ams{1..3},nyc{1..3},lon1,sfo1,sgp1,fra1}.digitalocean.co
 cdnTest="d2qm7ckles1o3d.cloudfront.net"
 userAgent="DigitalOcean Speed Test CLI $version - https://github.com/ZacharyDuBois/DigitalOcean-Speed-Test-CLI"
 testType=$1
+disallowTracking=$2
 
 
 ##
@@ -61,11 +62,11 @@ echo
 # Download Test
 ##
 
-echo "$notice All test files are not saved so you don't have to worry about disk space :P"
+echo "$info All test files are not saved so you don't have to worry about disk space :P"
 echo "$running Starting download speedtest..."
 
 # Determine the testType.
-if [[ $testType == "" ]]
+if [[ $testType == "100mb" ]] || [[ $testType == "" ]]
 then
   downloadFile="100mb.test"
   echo "$info You are running the 100MB test."
@@ -78,6 +79,18 @@ else
   exit 1
 fi
 
+if [[ $disallowTracking == false ]] || [[ $disallowTracking == "" ]]
+then
+  echo "$notice You have selected not to opt out of tracking. Tracking only counts the number of tests and the test type (and the IP will be logged in the access log, etc)."
+  echo "$notice The tracking URL is not called until the very end of the test. If you would like to opt out now, you can simply cancel this script and re-run it with the disallowTracking variable set. See README.md on Github for more information."
+elif [[ $disallowTracking == true ]]
+then
+  echo "$info You have selected to opt out of tracking. The tracking URI should not be called at the end."
+else
+  echo "$fail Unknown disallowTracking option."
+  exit 1
+fi
+
 downloadTest() {
   name=$1
   hostname=$2
@@ -85,9 +98,9 @@ downloadTest() {
 
   if [[ $ssl == true ]]
   then
-    $scheme="https://"
+    scheme="https://"
   else
-    $scheme="http://"
+    scheme="http://"
   fi
 
   echo "$running Running $name download speed test from $scheme$hostname/$downloadFile..."
@@ -102,8 +115,8 @@ do
 done
 
 echo "$info Starting CDN test. Test runs twice to ensure file is in the edge location."
-downloadTest "$cdnTest" "CDN Test 1x" true
-downloadTest "$cdnTest" "CDN Test 2x" true
+downloadTest "CDN Test 1x" "$cdnTest" true
+downloadTest "CDN Test 2x" "$cdnTest" true
 
 echo "$ok Download Speedtest."
 
@@ -139,6 +152,13 @@ done
 
 echo "$ok Latency test."
 
+if [[ $disallowTracking == false ]]
+then
+  echo "$running Calling tracking URL."
+  curl -s "https://we.destroy.tokyo/DOSTCLI-$testType" > /dev/null
+  echo "$ok Tracking compleate."
+else
+fi
 
 ##
 # Done
